version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "16:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@tailwindcss/postcss7-compat"
    versions:
    - 2.0.3
    - 2.0.4
    - 2.1.0
  - dependency-name: "@nuxtjs/tailwindcss"
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: nuxt
    versions:
    - 2.15.0
    - 2.15.1
    - 2.15.2
    - 2.15.3
  - dependency-name: "@nuxtjs/color-mode"
    versions:
    - 2.0.3
    - 2.0.4
